### ISSUE TITLE
请提供下readme.md 和 requitments.txt

### ISSUE THREAD

**Issue by lianglili** [ByZ0e/Glance-Focus#2]
你好，很感谢你分享代码！
      但是，你的代码中存在一下问题，请解答一下：
      （1）论文中，你报告了 STAR, EgoTaskQA, AGQA, and NExT-QA数据集上的实验结果，但代码中没有EgoTaskQA, AGQA, and NExT-QA。
     （2）我想复现你论文的实验结果，怎么做呢？请先补充完整的readme，保证其他研究者能够复现你论文的结果。
     （3）requirments.txt 在你的项目里不存在，请提供，保证环境的安装成功。

期待你的回复，谢谢

**Comment by ByZ0e** [comment]
感谢关注！
根据您的建议，我们更新了完整的README.md和requirments.txt。

**Comment by lianglili** [comment]
> 感谢关注！ 根据您的建议，我们更新了完整的README.md和requirments.txt。

非常感谢您的回复，请您提供一下AGQA数据集的特征，感谢！

**Comment by ByZ0e** [comment]
AGQA faster-rcnn的特征链接：https://drive.google.com/file/d/1s20vb6fUdfmFwflWnwLBRQckcj7ma4-y/view?usp=sharing
