### ISSUE TITLE
error in --losses_type for training

### ISSUE THREAD

**Issue by sjungz** [ByZ0e/Glance-Focus#4]
```
python train_glance_focus_uns.py --basedir expm/star --name gf_logs --device_id 0 --test_only 0 \
--qa_dataset star --base_data_dir $DEFAULT_DATASET_DIR \
--losses_type ['qa', 'cls', 'giou', 'cert']
```

I tried the above, and got the error:

```
usage: train_glance_focus_uns.py [-h] [--basedir BASEDIR] [--name NAME] [--device_id DEVICE_ID] [--batch_size BATCH_SIZE] [--nepoch NEPOCH] [--lr LR]
                                 [--i_val I_VAL] [--i_test I_TEST] [--i_print I_PRINT] [--i_weight I_WEIGHT] [--test_only TEST_ONLY]
                                 [--reload_model_path RELOAD_MODEL_PATH] [--hidden_dim HIDDEN_DIM] [--num_layers NUM_LAYERS]
                                 [--num_queries NUM_QUERIES] [--event_pred_dim EVENT_PRED_DIM] [--max_feats MAX_FEATS] [--qa_dataset QA_DATASET]
                                 [--task_type TASK_TYPE] [--num_options NUM_OPTIONS] [--output_dim OUTPUT_DIM] [--base_data_dir BASE_DATA_DIR]
                                 [--train_data_file_path TRAIN_DATA_FILE_PATH] [--test_data_file_path TEST_DATA_FILE_PATH]
                                 [--val_data_file_path VAL_DATA_FILE_PATH] [--event_anno_path EVENT_ANNO_PATH]
                                 [--action_mapping_path ACTION_MAPPING_PATH] [--app_feat_path APP_FEAT_PATH] [--feature_dim FEATURE_DIM]
                                 [--str2num_file STR2NUM_FILE] [--losses_type LOSSES_TYPE] [--qa_loss_coef QA_LOSS_COEF]
                                 [--cls_loss_coef CLS_LOSS_COEF] [--giou_loss_coef GIOU_LOSS_COEF] [--cert_loss_coef CERT_LOSS_COEF]
train_glance_focus_uns.py: error: unrecognized arguments: cls, giou, cert]
```

**Comment by ByZ0e** [comment]
Sorry for the extra blank sapces. Try `--losses_type ['qa','cls','giou','cert']`

**Comment by sjungz** [comment]
still got the same error

**Comment by ByZ0e** [comment]
the same? can you show the error message this time

**Comment by sjungz** [comment]
this is the error I got

losses_type ['[', 'q', 'a', ',', 'c', 'l', 's', ',', 'g', 'i', 'o', 'u', ',', 'c', 'e', 'r', 't', ']']
qa_loss_coef 1
cls_loss_coef 0.5
giou_loss_coef 0.5
cert_loss_coef 1
device cuda:0
  0%|                                                                                                                | 0/7150 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/Glance-Focus/train_glance_focus_uns.py", line 352, in <module>
    train(args)
  File "/home/Glance-Focus/train_glance_focus_uns.py", line 189, in train
    loss_dict = criterion(outputs, targets)
  File "/home/anaconda3/envs/vqa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Glance-Focus/model/glance_focus.py", line 241, in forward
    losses.update(self.get_loss(loss, outputs, targets))
  File "/home/Glance-Focus/model/glance_focus.py", line 228, in get_loss
    assert loss in loss_map, f'do you really want to compute {loss} loss?'
AssertionError: do you really want to compute [ loss?
  0%|                                                                                                                | 0/7150 [00:00<?, ?it/s]
  
  It seems like got loss type as a single character q, a, c, l, s, etc.

**Comment by ByZ0e** [comment]
Too wired.. Did you use the right losses list for losses_type argument? Maybe you can try with deleting this parameter and using the default setting.

**Comment by sjungz** [comment]
I deleted --losses_type argument and now it works. still need to check the results to make sure deleting the argument same with using every params
thanks!

**Comment by sjungz** [comment]
Hi, I think train worked successfully. But when I tried to run inference step with 
```
python train_glance_focus_uns.py --device_id 0 --test_only 1 \
--qa_dataset star --base_data_dir $DEFAULT_DATASET_DIR \
--reload_model_path expm/star/gf_logs/ckpts_2024-01-17T10-30-46/model_3000.tar \
(2024-01-17T10-30-46 is changed to the corresponding timeline that I run the train file)
```

and it showed this error

`FileNotFoundError: [Errno 2] No such file or directory: '/home/sjung/events/2024-03-01T00-02-20/submission_2024-03-01T00-02-20.json'`

I cannot find json file in events/(date) folder, is it related to the losses_type argument? how can I get this file?

**Comment by sjungz** [comment]
Hi I trained the model (10 epochs, default) and I want to try test file. ( when I run the inference, I got `TEST ACC: tensor(0.2442, device='cuda:0')` )
Can you provide the test file?

**Comment by sjungz** [comment]
Hi can you provide the test (or eval) file? I did training and inference and got `TEST ACC: tensor(0.2442, device='cuda:0')` as a result.

**Comment by ByZ0e** [comment]
STAR benchmark does not public labels for test set. You can submit the generated result file like `submission_XXX.json` to the public leaderboard [https://eval.ai/web/challenges/challenge-page/1325/overview](url) for testing.
