### ISSUE TITLE
Could you please share with me the processed files for AGQA, EGOTaskQA, NexT-QA datasets or corresponding data processing code for each benchmark and dataloader files for these dataset.

### ISSUE THREAD

**Issue by rejoicelf** [ByZ0e/Glance-Focus#5]
Could you please share with me the processed files for AGQA, EGOTaskQA, NexT-QA datasets or corresponding data processing code for each benchmark and dataloader files for these dataset?

**Comment by ByZ0e** [comment]
You can first try process the original data in the STAR format. We will share the processed files of other datasets later.

**Comment by rejoicelf** [comment]
But how to process corresponding data in the STAR format, could you share  processing code?
