### ISSUE TITLE
No such file or directory: 'expm/star/gf logs/events/logs/submission logs.json' 

### ISSUE THREAD

**Issue by xia-zhe** [ByZ0e/Glance-Focus#6]
1 When I used the checkpoints you provided for inference，I got a FileNotFoundError with the message "[Errno 2] No such file or directory: 'expm/star/gf logs/events/logs/submission logs.json'

2 Additionally, could you please provide some insight into why the accuracy is only 0.2556 after training with your features and following inference?

**Comment by ByZ0e** [comment]
1. Please check the right file path if you want to use different directory. We set the log directory in `log_dir = os.path.join(args.basedir, 'events', TIMESTAMP)` and the submission generate in `trans_results(results, os.path.join('/'.join(args.reload_model_path.split('/')[:3]), 'events', TIMESTAMP, 'submission_{}.json'.format(TIMESTAMP))).` 2. STAR benchmark does not public labels for test set. You can submit the generated result file like submission_XXX.json to the public leaderboard [https://eval.ai/web/challenges/challenge-page/1325/overview](https://github.com/ByZ0e/Glance-Focus/issues/url) for testing.

**Comment by xia-zhe** [comment]
Thank you very much for your response! I submitted the generated result file to the public leaderboard for testing but received a low score. Could there be an error?
![a6618fc73f611447467718889799650](https://github.com/ByZ0e/Glance-Focus/assets/139977177/16c95bdd-7972-4c77-a4f6-2f66f44eaebf)
![d169b12a900fc6c088a69eedd525b5c](https://github.com/ByZ0e/Glance-Focus/assets/139977177/b0626dcf-f59a-412e-9cae-2497bd536ebb)
（The terms 'origin' and 'test' represent the results of the submission.json file generated from the checkpoint you provided, and the results of the submission.json file obtained after training with the pre-trained features you provided, respectively.）

**Comment by xia-zhe** [comment]
Could you possibly provide links to the features extracted from the other datasets? I would like to achieve the same scores reported in your paper. Thank you very much！

**Comment by ByZ0e** [comment]
> Thank you very much for your response! I submitted the generated result file to the public leaderboard for testing but received a low score. Could there be an error? ![a6618fc73f611447467718889799650](https://private-user-images.githubusercontent.com/139977177/311946869-16c95bdd-7972-4c77-a4f6-2f66f44eaebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzIzOTYsIm5iZiI6MTcxMDIzMjA5NiwicGF0aCI6Ii8xMzk5NzcxNzcvMzExOTQ2ODY5LTE2Yzk1YmRkLTc5NzItNGM3Ny1hNGY2LTJmNjZmNDRlYWViZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwODI4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDkzZTE5MDQ1YTcwNzIyNmI5NGI2YjRjMmZiZGNjNTkwYWNlMjQ4ZDc1NWYyZWQxMzQ0NjEyZjJjYzA0NGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5EUSMXYBpD55U8efgA_t3nJWsAbZ2PH0dKn3oy55Elw) ![d169b12a900fc6c088a69eedd525b5c](https://private-user-images.githubusercontent.com/139977177/311946907-b0626dcf-f59a-412e-9cae-2497bd536ebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzIzOTYsIm5iZiI6MTcxMDIzMjA5NiwicGF0aCI6Ii8xMzk5NzcxNzcvMzExOTQ2OTA3LWIwNjI2ZGNmLWY1OWEtNDEyZS05Y2FlLTI0OTdiZDUzNmViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwODI4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWRlODE3NDczNGExODdkZGMyNTVjZjU2MGU4OTdjOGI0MTZhZWI4MmNjOWI0MzZjYTEyYzY0OTA0MTVhYWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xfv3x6rZBvm0XMW0cU0l__Kw4t0Eu_-94-aINEAe7xc) （The terms 'origin' and 'test' represent the results of the submission.json file generated from the checkpoint you provided, and the results of the submission.json file obtained after training with the pre-trained features you provided, respectively.）

Sorry for this bug in our codes. We missed the reload process during the testing. Therefore, you get predict results from a random initialized model. We have fixed the bug!
You can also add the following codes before the line `test_loss, test_acc, results = validate(model, test_dataloader, criterion, args)` :

```
optimizer = optim.Adam(model.parameters(), lr=args.lr)
if args.reload_model_path != '': 
        print('reloading model from', args.reload_model_path)
        reload_step = reload(model=model, optimizer=optimizer, path=args.reload_model_path)
```

**Comment by ByZ0e** [comment]
> Could you possibly provide links to the features extracted from the other datasets? I would like to achieve the same scores reported in your paper. Thank you very much！

Maybe you can try the suggested process code in README.md. We plan to upload the processed features of other datasets later. (Maybe not recently)

**Comment by xia-zhe** [comment]
> Owner

After making modifications, I got the following error when I ran the inference again:
Traceback (most recent call last):
  File "train_glance_focus_uns.py", line 357, in <module>
    test(args)
  File "train_glance_focus_uns.py", line 267, in test
    reload_step = reload(model=model, optimizer=optimizer, path=args.reload_model_path)
  File "train_glance_focus_uns.py", line 344, in reload
    model.load_state_dict(checkpoint['model_state_dict'])
  File "/uestcers/uestc1/.conda/envs/gfenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GF:
	size mismatch for event_class_embed.weight: copying a param with shape torch.Size([111, 512]) from checkpoint, the shape in current model is torch.Size([50, 512]).
	size mismatch for event_class_embed.bias: copying a param with shape torch.Size([111]) from checkpoint, the shape in current model is torch.Size([50]).

**Comment by rejoicelf** [comment]
I also meet the same errors.
Traceback (most recent call last):
  File "/data1/ghw_data/Glance-Focus/train_glance_focus_uns.py", line 357, in <module>
    test(args)
  File "/data1/ghw_data/Glance-Focus/train_glance_focus_uns.py", line 267, in test
    reload_step = reload(model=model, optimizer=optimizer, path=args.reload_model_path)
  File "/data1/ghw_data/Glance-Focus/train_glance_focus_uns.py", line 344, in reload
    model.load_state_dict(checkpoint['model_state_dict'])
  File "/home/ghw/anaconda3/envs/mc/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GF:
        size mismatch for event_class_embed.weight: copying a param with shape torch.Size([111, 512]) from checkpoint, the shape in current model is torch.Size([50, 512]).
        size mismatch for event_class_embed.bias: copying a param with shape torch.Size([111]) from checkpoint, the shape in current model is torch.Size([50]).

**Comment by ByZ0e** [comment]
The checkpoint may have inconsistency of the parameter of the `event_pred_dim`. Try temporally change this parameter to `111` may work. We will fix this bug.
