### ISSUE TITLE
关于数据处理问题的代码和脚本

### ISSUE THREAD

**Issue by rejoicelf** [ByZ0e/Glance-Focus#7]
Data Preprocessing
Please follow the data format in Option 1 to preper the corresponding data.
We also plan to upload the corresponding data processing code for each benchmark.

您好，在readme中的第二部分数据处理，如何按照STAR format的形式进行处理这些数据，有些数据集并没有strID2numID.json和action_mapping.txt以及events.json，请问可以上传数据处理的代码和脚本吗

**Comment by ByZ0e** [comment]
只需要提取相应数据集中所有的事件（动作）类别，制作events.json文件即可。strID2numID.json和action_mapping.txt是非必需的。相应地，dataloader里面需要做一些微小的数据读取调整。

**Comment by rejoicelf** [comment]
尝试的看了整个文件，strID2numID.json和action_mapping.txt是非必需的是只针对无监督的设定吧，请问可以把你的代码分享一下吗，感谢🙏

**Comment by rejoicelf** [comment]
请问，strID2numID.json和action_mapping.txt是非必需的只是对于无监督的设定吧

**Comment by ByZ0e** [comment]
都是非必需的。有监督的情况下，仅需要明确视频中的事件信息（时间戳和事件类别），这些信息都保存在events.json文件中即可。strID2numID.json是视频的文本到index对应关系，仅影响到特征读取；action_mapping.txt是事件类别到事件语义的对应关系，模型其实不需要事件语义信息。有时间的话建议阅读一下star.py文件了解数据集结构。
最近比较忙，之后有时间我们会再次维护本项目，敬请关注～
